### ISSUE TITLE
Migration failing with no case clause matching: {:aborted, {:bad_type, :id_seq....

### ISSUE THREAD

**Issue by vmoravec** [Nebo15/ecto_mnesia#16]
When trying to migrate [this simple migration](https://github.com/vmoravec/saturn/blob/master/priv/repo/migrations/20161210181650_create_user.exs) via mix ecto.migrate, it failing with:

```elixir
** (CaseClauseError) no case clause matching: {:aborted, {:bad_type, :id_seq, :disc_copies, :nonode@nohost}}
    lib/ecto_mnesia/storage/migrator.ex:134: Ecto.Mnesia.Storage.Migrator.do_create_table/4
    lib/ecto_mnesia/storage/migrator.ex:26: Ecto.Mnesia.Storage.Migrator.execute/3
    (ecto) lib/ecto/migrator.ex:43: Ecto.Migrator.migrated_versions/2
    (ecto) lib/ecto/migrator.ex:142: Ecto.Migrator.run/4
    (ecto) lib/mix/tasks/ecto.migrate.ex:84: anonymous fn/4 in Mix.Tasks.Ecto.Migrate.run/2
    (elixir) lib/enum.ex:651: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:651: Enum.each/2
    (mix) lib/mix/task.ex:296: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
    (elixir) lib/code.ex:363: Code.require_file/2
```

**Comment by vmoravec** [comment]
Have one more question, is the ordering of attributes in e.g. %User{} significant for mnesia? 
 ```elixir
iex(2)> %User{}          
%Saturn.User{__meta__: #Ecto.Schema.Metadata
<:built, "users">, email: nil, id: nil, inserted_at: nil, name: nil, updated_at: nil}
```
The attribute `id` is on second position, how to configure the Ecto.Schema to use `:id` for the `:set` engine?

**Comment by AndrewDryga** [comment]
Hello,

For Mnesia first key is a Table primary key, at this moment `ecto_mnesia` don't do anything with attributes order, so you should set it to be first manually.

**Comment by vmoravec** [comment]
Thanks for the prompt response, any hint what would be the right place to fix the attributes? The schema definition block in the migration doesn't seem to have any effect on that even if I add `add :id, :integer` there.

**Comment by AndrewDryga** [comment]
Can you show your migration and schema sources?

**Comment by vmoravec** [comment]
It's in the original issue description above. It's a plain phoenix app with added ecto_mnesia dependency and a single simple migration for `User`.

**Comment by AndrewDryga** [comment]
@vmoravec By default, `:id` field comes first in both migrations and schemas. And your code looks like email was created before `:id`:
```
%Saturn.User{__meta__: #Ecto.Schema.Metadata
<:built, "users">, email: nil, id: nil, inserted_at: nil, name: nil, updated_at: nil}
```

This is possible when multiple migrations change table, or when you decide to control primary keys manually.

**Comment by JanStevens** [comment]
How can this be fixed? I defined a very simple migration and just did an `ecto.create` and `ecto.migrate`

**Comment by AndrewDryga** [comment]
@JanStevens can you publish code somewhere in github?

**Comment by JanStevens** [comment]
Schema
```
defmodule DeviceServer.DeviceConfig do
  use DeviceServer.Web, :model
  alias __MODULE__

  #@type t :: %__MODULE__{}

  schema "device_configs" do
    field :uuid, :string
    field :environment, :string
    field :configs, :map
    timestamps()
  end
end
```

Migration
```
defmodule DeviceServer.Repo.Migrations.CreateConfigs do
  use Ecto.Migration

  def up do
    create_if_not_exists table(:device_configs) do
      add :uuid, :string
      add :environment, :string, default: "staging"
      add :configs, :map, default: %{}

      timestamps()
    end
  end

  def down do
    drop table(:device_configs)
  end
end
```

**Comment by JanStevens** [comment]
I setup a sample project, might be a bit easier:

https://github.com/JanStevens/devices_ex

**Comment by AndrewDryga** [comment]
@JanStevens try to disable SQL Sandbox mode in your `test/test_helper.ex` and in `test/support/*` files.

```
~/Projects/www/devices_ex(master ✗) mix test
Compiling 1 file (.ex)
==> Ensuring Mnesia data directory exists: priv/data/mnesia
==> Ensuring Mnesia schema exists
...

Finished in 0.04 seconds
3 tests, 0 failures

Randomized with seed 453229
```

**Comment by JanStevens** [comment]
@AndrewDryga Done, updated the repo but still the same problem. BTW I'm not talking about tests, just trying to do a `ecto.create` and `ecto.migrate`

**Comment by AndrewDryga** [comment]
@JanStevens @vmoravec Issue can be fixed by adding:
```
config :mnesia,
  dir: 'priv/data/mnesia'
```
to `config.ex`.

This happens because dir should be set before Mnesia app is started, I think that we will drop it from adapter's config.

**Comment by AndrewDryga** [comment]
Dropped it in latest commit. v0.6.1 should be ok now.

**Comment by cs-victor-nascimento** [comment]
Just to leave here for History, I had the same error from a different perspective. I did not call mix `ecto.create` before calling migrate. The error is a bit cryptic and took me a while to notice my dumbness...

Anyway, the dir config I am using something like this (which should work non-umbrella projects):

```elixir
mnesia_priv_path = "priv/data/mnesia_#{Mix.env()}"
mnesia_path = Path.join(File.cwd!(), mnesia_priv_path)

unless File.exists?(mnesia_path), do: File.mkdir_p!(mnesia_path)

config :mnesia,
  dir: to_charlist(mnesia_priv_path) 
```
