### ISSUE TITLE
Cannot create mnesia dir

### ISSUE THREAD

**Issue by JanStevens** [Nebo15/ecto_mnesia#17]
Hello,

Using latest version 0.6.5, I'm unable to run `mix ecto.create`, using the example project (from another issue): https://github.com/AndrewDryga/saturn

```
** (CaseClauseError) no case clause matching: {:error, {'Cannot create Mnesia dir', '/Users/fritz/PP/saturn/priv/mnesia/development', :enoent}}
    lib/ecto_mnesia/storage.ex:45: Ecto.Mnesia.Storage.storage_up/1
    lib/mix/tasks/ecto.create.ex:36: anonymous fn/3 in Mix.Tasks.Ecto.Create.run/1
    (elixir) lib/enum.ex:651: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:651: Enum.each/2
    (mix) lib/mix/task.ex:296: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
    (elixir) lib/code.ex:363: Code.require_file/2
```

If I create the dir myself everything works, didn't had this with version 0.6.1

**Comment by AndrewDryga** [comment]
This is not adapter issues, since I've dropped support of custom dirs from adapter config. 

You have set it directly for Mnesia (it's part of OTP), so Mnesia itself is trying create non-existent dir.
