### ISSUE TITLE
Ecto.Schema.Metadata state is built instead of loaded when retrieving a record

### ISSUE THREAD

**Issue by JanStevens** [Nebo15/ecto_mnesia#20]
When retrieving a saved record from Mnesia the record's state is built instead of `loaded` as one would expect

```
iex> TestRepo.get(SellOffer, 5)
%SellOffer{__meta__: #Ecto.Schema.Metadata<:built, "sell_offer">, age: nil,
 application: nil, book_value: nil, booked_at: nil, dividable: nil, dpc: nil,
 dpd: nil, ended_at: nil, guaranteed: nil, id: 5, income: nil,
 inserted_at: {{2016, 12, 20}, {14, 6, 1, 189118}}, loan_changes: nil,
 loan_currency: nil, loan_duration: nil, loan_id: nil, loan_oap: nil,
 loan_product_type: nil, loan_risk_class: nil, loan_risk_subclass: nil,
 loan_status: nil, max_shared_apr: nil, min_price_rate: nil, status: nil,
 trader_id: nil, updated_at: {{2016, 12, 20}, {14, 6, 1, 189123}}}
```

This is quite problematic when you want to call `insert_or_update`, it will always insert instead of calling update. A typical example (from the docs)

```
result =
  case MyRepo.get(Post, id) do
    nil  -> %Post{id: id} # Post not found, we build one
    post -> post          # Post exists, let's use it
  end
  |> Post.changeset(changes)
  |> MyRepo.insert_or_update

case result do
  {:ok, struct}       -> # Inserted or updated with success
  {:error, changeset} -> # Something went wrong
end
```

When inserting or deleting a record the returned element is `loaded` or `deleted`.

**Comment by JanStevens** [comment]
Possible fix (again this seems quite hackisch) is to manually update the state to `loaded` when building the resulting from mnesia. In `ecto_mnesia/record.ex:39`

```elixir
  defp get_result_type(%Ecto.Query.SelectExpr{expr: {:&, [], [0]}}, schema) do
    schema.__struct__ |> put_meta(state: :loaded)
  end
```

I don't really get how the state is managed in ecto so this could be pretty bad

**Comment by AndrewDryga** [comment]
Hm. Let me check.

Internally Ecto have two interfaces: 
1. `execute/6` and `insert` that accepts raw list of return values as keyword map. There Ecto manages schema creation and state manually.

2. Adapter methods for insert, get, etc. Where schema should be returned manually.

So you may be right about solution :).
