### ISSUE TITLE
** (RuntimeError) Schema :id_seq does not exist

### ISSUE THREAD

**Issue by gallexme** [Nebo15/ecto_mnesia#27]
=INFO REPORT==== 13-Mar-2017::20:23:11 ===
    application: logger
    exited: stopped
    type: temporary
** (Mix) Could not start application crypto_exchange: CryptoExchange.Application.start(:normal, []) returned an error: shutdown: failed to start child: CryptoExchange.CryptoCrawler
    ** (EXIT) an exception was raised:
        ** (RuntimeError) Schema :id_seq does not exist
            (ecto_mnesia) lib/ecto_mnesia/table.ex:152: Ecto.Mnesia.Table.transaction/2
            (ecto_mnesia) lib/ecto_mnesia/adapter.ex:250: Ecto.Mnesia.Adapter.transaction/3
            (elixir) lib/enum.ex:645: Enum."-each/2-lists^foreach/1-0-"/2
            (elixir) lib/enum.ex:645: Enum.each/2
            (crypto_exchange) lib/crypto_exchange/crypto_crawler.ex:15: CryptoExchange.CryptoCrawler.init/1
            (stdlib) gen_server.erl:328: :gen_server.init_it/6
            (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
PS C:\Users\Fabi\Desktop\Dev\web\crypto_exchange_umbrella> ** (RuntimeErro

my schemas:
defmodule CryptoExchange.Currencies do
  @moduledoc false
  use Ecto.Schema

  schema "currencies" do
    field :long_name, :string
    has_many :currencies_data, CryptoExchange.CurrenciesData
    field :short_name, :string
  end
end
defmodule CryptoExchange.CurrenciesData do
  @moduledoc false
  use Ecto.Schema
@primary_key false
  schema "currencies_data" do
    belongs_to :base, CryptoExchange.Currencies
    belongs_to :target, CryptoExchange.Currencies
    field :timestamp, :integer
    field :price, :float
    timestamps
  end
end

any idea?

**Comment by AndrewDryga** [comment]
This duplicates #26. Can you answer on the question i've posted there?
