### ISSUE TITLE
Updating a field to `nil` is ignored

### ISSUE THREAD

**Issue by scrogson** [Nebo15/ecto_mnesia#28]
I'm unable to set a column to `nil` in an update. I've tracked it down to this [line](https://github.com/Nebo15/ecto_mnesia/blob/master/lib/ecto_mnesia/table.ex#L70).

Is this desirable?

Since `Repo.update` only works with a changeset, it seems appropriate to allow columns to be set to `nil` if they are included in the `changes` key.

**Comment by AndrewDryga** [comment]
Thats a logical bug, you definitely must be able to write whatever you want.

**Comment by AndrewDryga** [comment]
Fixed in latest release
