### ISSUE TITLE
Repository creation fails

### ISSUE THREAD

**Issue by adamdaugherty** [Nebo15/ecto_mnesia#31]
I am using ecto_mnesia 0.7.1, ecto 2.1.4, Elixir 1.4.2, with the following configuration:

```elixir
config :ecto_mnesia, host: node(), storage_type: :disc_copies
config :mnesia, dir: "priv/my_app/mnesia"
config :my_app, :ecto_repos, [MyApp.Repo]
config :my_app, MyApp.Repo, adapter: Ecto.Adapters.Mnesia
```

When I run `mix ecto.create`, the `dir` defined above (`priv/my_app/mnesia`) is created, and then the following occurs:

```
==> Setting Mnesia schema table copy type
==> Ensuring Mnesia schema exists
** (CaseClauseError) no case clause matching: {:error, {:EXIT, :function_clause}}
    lib/ecto_mnesia/storage.ex:46: Ecto.Mnesia.Storage.storage_up/1
    lib/mix/tasks/ecto.create.ex:36: anonymous fn/3 in Mix.Tasks.Ecto.Create.run/1
    (elixir) lib/enum.ex:645: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:645: Enum.each/2
    (mix) lib/mix/task.ex:294: Mix.Task.run_task/3
    (mix) lib/mix/project.ex:313: Mix.Project.in_project/4
    (elixir) lib/file.ex:1162: File.cd!/2
    (mix) lib/mix/task.ex:394: anonymous fn/4 in Mix.Task.recur/1
```

In the course of investigating the problem, I started looking at the `storage_up` and `conf` functions in `storage.ex`, since that's where the error was occurring. Strangely, if I manually call `:mnesia.create_schema [node()]` in `iex` (which is the same thing that `storage_up` is doing when it falls over), it results in `{:error, {:nonode@nohost, {:already_exists, :nonode@nohost}}}`, which the `case` in `storage_up` expects.

If I add a call to `:mnesia.start` after `change_table_copy_type` but before `create_schema` in `storage_up`, it seems to work. I'm not sure if this is a flaw in `ecto_mnesia` or if I somehow need to start mnesia myself or configure something to do it for me, and I haven't been able to find any guidance online.

While probably unrelated to my issue, I also noticed that the `:ecto_mnesia` configuration I had set was simply being ignored. The defaults were being used all of the time, as the `config` parameter being passed into the `conf` function was `[otp_app: :my_app, repo: MyApp.Repo, adapter: Ecto.Adapters.Mnesia]`, not the `[host: ..., storage_type: ...]` that it appears to be expecting. I'm not making it a separate issue, just in case all of this is the result of some misconfiguration or something.

**Comment by AndrewDryga** [comment]
Hello, and thanks for a feedback 👍.

First of all error that contains `:function_clause` means that there was some data that Erlang wasn't able to pattern match agains function. Do you have any migrations in your project?

**Comment by adamdaugherty** [comment]
I tried it both with and without migrations, as I was just trying to get things nominally working. It didn't seem to make a difference with respect to this issue. I also tried both with and without the mnesia directory on disk, as well as messing around with different configurations, but they all had the same result.

**Comment by AndrewDryga** [comment]
Can you create a sample repository where issues can be reproduced? I'll take look at it

**Comment by adamdaugherty** [comment]
Sure thing, but it'll have to wait until Monday.

**Comment by adamdaugherty** [comment]
I've created a repo to demonstrate the issue [here](https://github.com/adamdaugherty/ecto_mnesia_issue_31). The steps to recreate the issue are fairly straightforward:

```bash
mix deps.get
mix ecto.create
```

Please let me know if there's anything else you need, or if you have any questions. Hopefully, I'm just doing something stupid and obvious and this doesn't result in you having to make any changes. Thanks a bunch for your help, either way.

**Comment by AndrewDryga** [comment]
You need to do two actions:
1. Mnesia path is specified as charlist, replace `"` with `'` in config.ex:
  ```
  config :mnesia, dir: 'priv/my_app/mnesia'
  ```

2. Create dir at first:
  ```
  $ mkdir -p mkdir -p priv/my_app/mnesia
  ```
  Mnesia don't create data dir by itself.

Result:
```
 mix ecto.create            
==> Setting Mnesia schema table copy type
==> Ensuring Mnesia schema exists
The database for MyApp.Repo has been created
```

**Comment by AndrewDryga** [comment]
Added warnings about charlist to latest release.

**Comment by adamdaugherty** [comment]
Thanks a bunch for your help, that solved it. I really appreciate your help.

You might want to investigate the issue I mentioned as an aside, as it still seems to be present, at least during `mix ecto.config`. The `conf` function in `lib/ecto_mnesia/storage.ex` is being passed a keyword list that looks like `[otp_app: :my_app, repo: MyApp.Repo, adapter: Ecto.Adapters.Mnesia]`, not `[host: whatever, storage_type: whatever]`, so the defaults are always being used.

If you add an `IO.inspect config` on line 62 of `storage.ex` and `mix ecto.create`, you'll see what I mean.

**Comment by AndrewDryga** [comment]
@adamdaugherty Thanks, Ill take look into it

**Comment by sneako** [comment]
@adamdaugherty I noticed that (about the defaults) as well. I have to set MNESIA_HOST and MNESIA_STORAGE_TYPE env vars to change those values
