### ISSUE TITLE
order_by: and limit: seem to be EXTREMELY slow

### ISSUE THREAD

**Issue by Qqwy** [Nebo15/ecto_mnesia#65]
Unless I am mistaken (and please tell me if I am; it would make me very happy ^.^), the ordering and limiting behaviour that EctoMnesia uses is emulated in a highly non-scalable way:

- First, everything is selected from the database
- Then, everything is sorted to adhere to the `order_by` statement (using `Enum.sort` and the like)
- Then, we chop off the tail, to adhere to the `limit`.

This means that any and all selection procedures, regardless of how few results we want to return run in `O(n * log n)`, which is extremely unacceptable for all but the smallest datasets (like ones that will never grow).

I am referring to locations like: 

https://github.com/Nebo15/ecto_mnesia/blob/master/lib/ecto_mnesia/planner.ex#L43

-----

## Proposal:

1. Since this is a **very** significant limitation of this adapter vs. other adapters, make this clear in the README.
2. It might also be possible to display warnings when people do try to use `order_by:` and `limit:` statements in their code, to tell them that it is really slow.
2. If we were to wrap `qlc`, we might be able to have proper support for order_by and limit, although I am not enough of an expert on `qlc` to be entirely certain.

**Comment by AndrewDryga** [comment]
@Qqwy I've updated the readme. QLC is definitely an option and PR would be super-appreciated (I'll buy you a bear :).
