### ISSUE TITLE
Will this adapter be updated to Ecto v3?

### ISSUE THREAD

**Issue by English3000** [Nebo15/ecto_mnesia#75]
Hey,

I am using your adapter for a few internal tools.

I see that it's been almost 4 months since the [release of Ecto v3](https://github.com/elixir-ecto/ecto/releases).

When do you think support for it will be added?

**Comment by AndrewDryga** [comment]
@English3000 I'm sorry, but I can't give ETA as my hands are all busy however a PR would be welcome. There were few attempts but it's not easy as you might think :).
